// <auto-generated />
using System;
using Lanre.Data.Context.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lanre.Data.Context.Migrations.Schedule
{
    [DbContext(typeof(SchedulerContext))]
    partial class SchedulerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lanre.Infrastructure.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2018, 8, 15, 13, 57, 9, 477, DateTimeKind.Local));

                    b.HasKey("Id");

                    b.ToTable("Appointments");

                    b.HasData(
                        new { Id = new Guid("a09c1e14-d823-4281-926d-345299696beb"), EntryDate = new DateTime(2018, 8, 15, 13, 57, 9, 479, DateTimeKind.Local) },
                        new { Id = new Guid("7fa0d8be-83b2-45fa-b3ce-e40b6195beaa"), EntryDate = new DateTime(2018, 8, 15, 13, 57, 9, 479, DateTimeKind.Local) },
                        new { Id = new Guid("7dc436a5-29b9-475d-a394-f97a691f74f3"), EntryDate = new DateTime(2018, 8, 15, 13, 57, 9, 479, DateTimeKind.Local) },
                        new { Id = new Guid("e4fb1be6-4ba7-40c7-beef-e2b8c32751b6"), EntryDate = new DateTime(2018, 8, 15, 13, 57, 9, 479, DateTimeKind.Local) },
                        new { Id = new Guid("4da90981-6a19-48a1-a6d0-c1f413dc748d"), EntryDate = new DateTime(2018, 8, 15, 13, 57, 9, 479, DateTimeKind.Local) },
                        new { Id = new Guid("1849dfa8-9fac-4b0c-a63f-e3198935dc7b"), EntryDate = new DateTime(2018, 8, 15, 13, 57, 9, 479, DateTimeKind.Local) },
                        new { Id = new Guid("dc8fabd1-09b6-427f-8454-2066a70d2828"), EntryDate = new DateTime(2018, 8, 15, 13, 57, 9, 479, DateTimeKind.Local) },
                        new { Id = new Guid("c66f9fae-ea7c-43cf-b5bf-54f9164489f8"), EntryDate = new DateTime(2018, 8, 15, 13, 57, 9, 479, DateTimeKind.Local) },
                        new { Id = new Guid("f5950a6f-a698-4393-a9a5-5441cd03b1f7"), EntryDate = new DateTime(2018, 8, 15, 13, 57, 9, 479, DateTimeKind.Local) }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
